apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-demo-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-demo-app
  template:
    metadata:
      labels:
        app: vault-demo-app
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: DB_USERNAME
          value: <path:secret/data/myapp/database#username>
        - name: DB_PASSWORD
          value: <path:secret/data/myapp/database#password>
        - name: DB_HOST
          value: <path:secret/data/myapp/database#host>
        - name: API_KEY
          value: <path:secret/data/myapp/api#key>
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config
        configMap:
          name: app-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Vault + Argo CD Integration Demo</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
            .container { background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .secret { background: #e8f5e8; padding: 15px; margin: 10px 0; border-radius: 4px; border-left: 4px solid #4caf50; }
            h1 { color: #333; }
            .note { background: #fff3cd; padding: 10px; border-radius: 4px; border-left: 4px solid #ffc107; margin: 20px 0; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Vault + Argo CD Integration Demo</h1>
            <p>This application demonstrates how Argo CD can fetch secrets from HashiCorp Vault during deployment.</p>
            
            <div class="note">
                <strong>Note:</strong> In production environments, secrets should never be displayed in user interfaces. 
                This demonstration is for educational purposes only.
            </div>
            
            <h2>Secrets Retrieved from Vault:</h2>
            <div class="secret">
                <strong>Database Username:</strong> <path:secret/data/myapp/database#username>
            </div>
            <div class="secret">
                <strong>Database Host:</strong> <path:secret/data/myapp/database#host>
            </div>
            <div class="secret">
                <strong>API Endpoint:</strong> <path:secret/data/myapp/api#endpoint>
            </div>
            
            <h2>Implementation Process:</h2>
            <ol>
                <li>ArgoCD detects changes in the Git repository</li>
                <li>The Vault plugin processes manifests with <code>&lt;path:...&gt;</code> placeholders</li>
                <li>Plugin authenticates to Vault using Kubernetes auth</li>
                <li>Secrets are fetched and injected into the manifests</li>
                <li>Final manifests are applied to Kubernetes</li>
            </ol>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: vault-demo-app
  namespace: default
spec:
  selector:
    app: vault-demo-app
  ports:
  - port: 80
    targetPort: 80
  type: NodePort

# 4 June 2025 : Changed username 5:26PM